// data/CourseData.js
export const courses = [
  {
    id: 1,
    title: "Web Development",
    description: "Learn full-stack web development with modern technologies like React, Node.js, and MongoDB. Build real-world projects and become a professional web developer.",
    image: "webdev.webp",
    instructor: "....",
    duration: "14 weeks",
    level: "Beginner to Advanced",
    price: 399,
    rating: 4.8,
    students: "##",
    category: "Development",
    features: ["HTML/CSS", "JavaScript", "React", "Node.js", "MongoDB", "Deployment"],
    popular: true
  },
  {
    id: 2,
    title: "Microsoft Office",
    description: "Master Microsoft Office suite including Word, Excel, PowerPoint, and Outlook. Boost your productivity and professional skills.",
    image: "office.png",
    instructor: "....",
    duration: "8 weeks",
    level: "All Levels",
    price: 139,
    rating: 4.6,
    students: "##",
    category: "Productivity",
    features: ["Word", "Excel", "PowerPoint", "Outlook", "Advanced Formulas", "Automation"],
    popular: false
  },
  {
    id: 3,
    title: "C programming",
    description: "Learn C programming fundamentals and build efficient, low-level applications.",
    image: "c.webp",
    instructor: "....",
    duration: "10 weeks",
    level: "Intermediate",
    price: 199,
    rating: 4.7,
    students: "##",
    category: "Development",
    features: ["C Programming", "Pointers", "Memory Management", "Data Structures"],
    popular: true
  },
  {
    id: 4,
    title: "java",
    description: "Learn Java programming from scratch and build robust applications.",
    image: "java.webp",
    instructor: "....",
    duration: "10 weeks",
    level: "Beginner",
    price: 199,
    rating: 4.9,
    students: "###",
    category: "Development",
    features: ["Java", "Object-Oriented Programming", "Collections", "Exception Handling"],
    popular: true
  },
  {
    id: 5,
    title: "php",
    description: "Master PHP for web development and create dynamic websites and applications.",
    image: "php.webp",
    instructor: ".....",
    duration: "12 weeks",
    level: "All Levels",
    price: 399,
    rating: 4.5,
    students: "###",
    category: "Development",
    features: ["PHP", "MySQL", "Web Development", "Security", "Database Integration"],
    popular: false
  },
  {
    id: 6,
    title: "DBMS",
    description: "Learn database management systems and SQL for efficient data handling.",
    image: "dbms.png",
    instructor: "....",
    duration: "10 weeks",
    level: "Advanced",
    price: 229,
    rating: 4.7,
    students: "###",
    category: "Development",
    features: ["Database Management", "SQL", "Normalization", "Transactions", "ER Diagrams"],
    popular: true
  },
  {
    id: 7,
    title: "Digital Marketing",
    description: "Learn the fundamentals of digital marketing including SEO, social media marketing, and email marketing to grow your online presence.",
    image: "digimark.png",
    instructor: "....",
    duration: "10 weeks",
    level: "Beginner to Intermediate",
    price: 229,
    rating: 4.7,
    students: "###",
    category: "Marketing",
    features: ["SEO", "Social Media Marketing", "Email Marketing", "Analytics", "Content Strategy"],
    popular: true,
  },
  {
    id: 8,
    title: "Tally",
    description: "Master Tally ERP 9 for efficient accounting and financial management in businesses.",
    image: "tally.webp",
    instructor: "....",
    duration: "8 weeks",
    level: "Beginner to Intermediate",
    price: 229,
    rating: 4.7,
    students: "###",
    category: "Productivity",
    features: ["Tally ERP 9", "Accounting", "Financial Management", "Inventory Management"],
    popular: false
  },
  {
    id: 9,
    title: "Microsoft Word",
    description: "Become proficient in Microsoft Word for document creation, formatting, and editing.",
    image: "word.avif",
    instructor: "....",
    duration: "4 weeks",
    level: "Beginner to Intermediate",
    price: 99,
    rating: 4.7,
    students: "###",
    category: "Productivity",
    features: ["Document Creation", "Formatting", "Editing", "Templates", "Collaboration"],
    popular: false
  },
  {
    id: 10,
    title: "Microsoft Excel",
    description: "Become proficient in Microsoft Excel for data analysis, spreadsheet creation, and advanced calculations.",
    image: "excel.webp",
    instructor: "....",
    duration: "4 weeks",
    level: "Beginner to Intermediate",
    price: 99,
    rating: 4.7,
    students: "###",
    category: "Productivity",
    features: ["Data Analysis", "Spreadsheet Creation", "Advanced Calculations", "Charts and Graphs", "Pivot Tables"],
    popular: false
  },
  {
    id: 11,
    title: "Microsoft PowerPoint",
    description: "Master Microsoft PowerPoint for creating engaging presentations with multimedia elements and effective design principles.",
    image: "powerpoint.png",
    instructor: "....",
    duration: "4 weeks",
    level: "Beginner to Intermediate",
    price: 99,
    rating: 4.7,
    students: "###",
    category: "Productivity",
    features: ["Data Analysis", "Spreadsheet Creation", "Advanced Calculations", "Charts and Graphs", "Pivot Tables"],
    popular: false
  },
  {
    id: 12,
    title: "Python",
    description: "Learn Python programming from basics to advanced concepts and build real-world applications.",
    image: "python.png",
    instructor: "....",
    duration: "10 weeks",
    level: "Beginner to Intermediate",
    price: 199,
    rating: 4.7,
    students: "###",
    category: "Development",
    features: ["Python Programming", "Data Structures", "Algorithms", "Web Development", "Machine Learning"],
    popular: true
  },
  {
    id: 13,
    title: "Email & Internet",
    description: "Master email communication and internet skills for personal and professional use.",
    image: "email&internet.webp",
    instructor: "....",
    duration: "6 weeks",
    level: "Beginner to Intermediate",
    price: 229,
    rating: 4.7,
    students: "###",
    category: "Productivity",
    features: ["Email Communication", "Internet Skills", "Email Setup", "Internet Navigation", "Online Safety"],
    popular: false
  },
  {
    id: 14,
    title: "Canva",
    description: "Learn Canva for graphic design and create stunning visuals for social media, presentations, and marketing materials.",
    image: "canva.png",
    instructor: "....",
    duration: "7 weeks",
    level: "Beginner to Advanced",
    price: 179,
    rating: 4.6,
    students: "###",
    category: "Design",
    features: ["Graphic Design", "Multimedia Design", "Branding", "Social Media Graphics", "Presentation Design"],
    popular: false
  },
];

export const categories = [
  "All",
  "Development",
  "Design",
  "Marketing",
  "Productivity"
];

export default { courses, categories };